#!/bin/bash

SHELL_NAME=$(basename $SHELL)
echo $SHELL_NAME

# Check to see if pyenv is on the path.
pyenv --version > /dev/null
if [ $? -ne 0 ]
then
    # Install pyenv if not found.
    curl https://pyenv.run | $SHELL
fi

# Check to see if pyenv has been added to the path.
cat ~/.${SHELL_NAME}rc | grep 'export PATH="~/.pyenv/bin:$PATH"' > /dev/null
if [ $? -ne 0 ]
then
    # Add pyenv to your path.
    echo 'export PATH="~/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"' >> ~/.${SHELL_NAME}rc

    # Update PATH
    export PATH="~/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

PYTHON_VERSION=3.8.3

# Ensure Python is installed
pyenv versions | grep $PYTHON_VERSION > /dev/null
if [ $? -ne 0 ]
then
    # Install Python
    pyenv install $PYTHON_VERSION
fi
pyenv local $PYTHON_VERSION

# Ensure pipx
pip list | grep pipx > /dev/null
if [ $? -ne 0 ]
then
    # Install pipx
    pip install pipx
    pipx ensurepath

    echo Please restart Bash.
    exit
fi

python ./cli.py $@
