#!/bin/bash

if [ "$(uname)" == "Darwin" ]; then
    ./cli-mac $@ 
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    ./cli-linux $@
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    powershell.exe -File ./cli.ps1 -ArgumentList  $@
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    powershell.exe -File ./cli.ps1 -ArgumentList  $@
fi