#!/bin/bash

function BrewInstallCask {
    brew list --cask | grep $1 > /dev/null
    if [ $? -ne 0 ]
    then
        brew install --cask $1
    fi
}

# Install dependencies
BrewInstallCask xquartz
BrewInstallCask virtualbox
BrewInstallCask vagrant

MEMORY=`sysctl -a | grep '^hw\.m' | awk -F": " '/hw.memsize:/ { print $2 }'`
VAGRANT_MEMORY=`echo "($MEMORY*0.6)/(1024^2)" | bc`

CPUS=`sysctl -a | grep '^machdep\.cpu\.core_count' | awk -F": " '/machdep.cpu.core_count:/ { print $2 }'`
VAGRANT_CPUS=$(( $CPUS / 2 ))


echo "vb:" > env.yml
echo "  cpus: $VAGRANT_CPUS" >> env.yml
echo "  memory: $VAGRANT_MEMORY" >> env.yml

WIDTH=`system_profiler SPDisplaysDataType | grep Resolution | awk -F": " '/Resolution:/ { print $2 }' | awk -F" x " '{ print $1 }'`
HEIGHT=`system_profiler SPDisplaysDataType | grep Resolution | awk -F": " '/Resolution:/ { print $2 }' | awk -F" x " '{ print $2 }' | awk -F" " '{ print $ 1 }'`

VIRTUALBOX_IP_Address=`ifconfig vboxnet0 | awk '$1 == "inet" {print $2}'`

vagrant status | grep 'running' > /dev/null
if [ $? -ne 0 ]
then
    vagrant up
fi

vagrant -Y ssh -- -t "export DISPLAY=$VIRTUALBOX_IP_Address:0.0; export WIDTH=$WIDTH; export HEIGHT=$HEIGHT; cd /baboon-tracking; ./cli $@"

ps | grep 'vagrant' > /dev/null
if [ $? -ne 0 ]
then
    vagrant suspend
fi
