#!/bin/bash -i

# SCRIPT_RELATIVE_DIR=$(dirname "${BASH_SOURCE[0]}")
# cd $SCRIPT_RELATIVE_DIR
# DIR=`pwd`

cd ~/Repos/school/baboon-tracking

while true
do
    git pull && ./cli optimize -d $DATASET -t yes -p no -w $MAX_WIDTH -l $MAX_HEIGHT -o $ALLOW_OVERLAP
done