#! /bin/bash

get_cuda_cc() {
    SERIES=`echo $GPU | grep -oP "10(?=[0-9]{2})"`

    case $SERIES in
        10)
            echo "6.1"
            ;;

        20)
            echo "7.5"
            ;;

        30)
            echo "8.6"
            ;;

        *)
            echo -n "unknown"
            ;;
    esac
}

use_cpu() {
    echo "No CUDA capable device found.  Using CPU..."
}

DIR=`dirname $0`
DIR=`realpath $DIR`
echo $DIR

lspci | grep NVIDIA > /dev/null
if [ $? -eq 0 ]
then
    #NVIDIA
    GPU=`lspci | grep NVIDIA | grep -oP "(?<=\[).+(?=\])"`
    CC=`get_cuda_cc "$GPU"`

    if  [[ $CC == "unknown" ]]
    then
        use_cpu
    else
        echo "Discovered $GPU. Using CUDA CC $CC..."

        case $1 in
            run)
                docker run -it --gpus all -v $DIR/build:/data "ghcr.io/ucsd-e4e/baboon-tracking:cuda-$CC"
                ;;
            shell)
                docker run -it --gpus all -v $DIR/build:/data "ghcr.io/ucsd-e4e/baboon-tracking:cuda-$CC" /bin/bash
                ;;
            *)
                echo help
                ;;
        esac
    fi
else
    #CPU

    use_cpu
fi