#! /bin/bash

get_cuda_cc() {
    SERIES=`echo $GPU | grep -oP "10(?=[0-9]{2})"`

    case $SERIES in
        10)
            echo "6.1"
            ;;

        20)
            echo "7.5"
            ;;

        30)
            echo "8.6"
            ;;

        *)
            echo -n "unknown"
            ;;
    esac
}

use_cpu() {
    echo "No CUDA capable device found.  Using CPU..."
}

DIR=`dirname $0`
DIR=`realpath $DIR`
echo $DIR

nvidia-smi > /dev/null
if [ $? -ne 0 ]
then
  #CPU
  use_cpu
else
  #NVIDIA
  CC=`nvidia-smi --query-gpu=compute_cap --format=csv | grep -oP "[0-9]\.[0-9]"`
  if ([ "$CC" != "6.1" ] && [ "$CC" != "7.5" ] && [ "$CC" != "8.1" ])
  then
    #unsupported/unknown CC
    echo "Unknown or unsupported CC"
    use_cpu
  else
    echo "Discovered GPU. Using CUDA CC $CC..."
    case $1 in
      run)
          docker run -it --gpus all -v $DIR/build:/data "ghcr.io/ucsd-e4e/baboon-tracking:cuda-$CC"
          ;;
      shell)
          docker run -it --gpus all -v $DIR/build:/data "ghcr.io/ucsd-e4e/baboon-tracking:cuda-$CC" /bin/bash
          ;;
      *)
          echo help
          ;;
    esac
  fi
fi